name = "example"
version = "0.1.0"
description = ""
license = "MIT"

[neutralino]
applicationId = "js.neutralino.${name}"
version = "${version}"
defaultMode = "window"
port = 0
documentRoot = "/resources/"
url = "/"
enableServer = true
enableNativeAPI = true
enableExtensions = true
exportAuthInfo = true
tokenSecurity = "one-time"
nativeAllowList = ["app.*", "os.*", "extensions.*", "debug.log"]

[[neutralino.extensions]]
id = "js.neutralino.${name}.python"
command = "${python} -m extensions.python"

[neutralino.logging]
enabled = true
writeToLogFile = true

[neutralino.globalVariables]
[neutralino.modes.window]
title = "${name} - ${version}"
width = 800
height = 500
minWidth = 400
minHeight = 200
fullScreen = false
alwaysOnTop = false
icon = "/resources/icons/appIcon.png"
enableInspector = true
borderless = false
maximize = false
hidden = false
resizable = true
exitProcessOnClose = false

[neutralino.modes.browser]

[neutralino.modes.cloud]

[neutralino.modes.chrome]

[neutralino.cli]
binaryName = "${name}"
resourcesPath = "/resources/"
extensionsPath = "/extensions/"
clientLibrary = "/resources/js/neutralino.js"
binaryVersion = "4.4.0"
clientVersion = "3.3.0"
[poetry.tool.poetry]
name = "${name}-python"
version = "${version}"
description = "${description}"
license = "${license}"
authors = []

[[poetry.tool.poetry.packages]]
include = "extensions/${name}"

[poetry.tool.poetry.dependencies]
python = "^3.8"
websocket-client = "^1.3.3"
rel = "^0.4.7"

[poetry.tool.poetry.dev-dependencies]

[poetry.build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
