site_name: neutrapy
repo_url: https://github.com/pwwang/neutrapy
repo_name: pwwang/liquidpy
theme:
    favicon: favicon.png
    logo: favicon.png
    icon:
        repo: fontawesome/brands/github
    name: 'material'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    features:
        - navigation.top
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.magiclink
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
nav:
    - 'Home': 'index.md'
    - 'The CLI tool': 'cli.md'
    - 'App-to-extension communication': 'app-to-extension.md'
    - 'The python extension': 'extension.md'
    - 'Useful links': 'links.md'
    - 'CHANGELOG': 'CHANGELOG.md'
